import requests

offset = 0
url_template = 'https://www.skipperi.fi/api/boats?brand&capacity&club&country=all&keyword&location=&offset={offset}&order&type=sailing_boat'
data = requests.get(url = url_template.format(offset=offset)).json()
results = []
skipped_because_no_price = 0
while data and data['boats']:
    for vessel in data['boats']:
        if not vessel['prices']:
            skipped_because_no_price += 1
            continue
        lat, long = vessel['boat_locations'][0]['point']['coordinates']
        link = f'www.skipperi.fi{vessel["url"]}'
        price_str, currency = vessel['prices']['price'].split(' ')
        price = float(price_str)
        if currency == 'kr':
            price *= 0.086 # to eur
        if vessel['prices']['type'] == 'week':
            price = price / 7
        parsed_vessel = {'lat': lat, 'long': long, 'link': link, 'price': price}
        results.append(parsed_vessel)
    print(f'Processed offset {offset}')
    offset += 1
    data = requests.get(url = url_template.format(offset=offset)).json()
print(len(results))

with open("result.kml", "w") as f:
    f.write("""<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/kml/2.2 http://schemas.opengis.net/kml/2.2.0/ogckml22.xsd">
  <Document>
    <name>Map - July 27, 2024</name>
    <description><![CDATA[Generated by AllTrails https://www.alltrails.com/]]></description>
    <Style id="gpsiesStyle">
      <IconStyle>
        <scale>0.5</scale>
        <Icon>
          <href>https://www.gpsies.com/images/milestone.png</href>
        </Icon>
      </IconStyle>
      <LineStyle>
        <colorMode>random</colorMode>
        <width>5</width>
      </LineStyle>
    </Style>
    <Style id="flag_n">
      <IconStyle>
        <scale>0.8</scale>
        <Icon>
          <href>https://www.gpsies.com/images/flag.png</href>
        </Icon>
      </IconStyle>
      <LabelStyle>
        <scale>0</scale>
      </LabelStyle>
      <BalloonStyle>
        <text>$[description]</text>
      </BalloonStyle>
    </Style>
    <Style id="flag_h">
      <IconStyle>
        <scale>0.8</scale>
        <Icon>
          <href>https://www.gpsies.com/images/flag.png</href>
        </Icon>
      </IconStyle>
      <LabelStyle>
        <scale>1</scale>
      </LabelStyle>
      <BalloonStyle>
        <text>$[description]</text>
      </BalloonStyle>
    </Style>
    <StyleMap id="flag">
      <Pair>
        <key>normal</key>
        <styleUrl>#flag_n</styleUrl>
      </Pair>
      <Pair>
        <key>highlight</key>
        <styleUrl>#flag_h</styleUrl>
      </Pair>
    </StyleMap>
    <Style id="generic_n">
      <IconStyle>
        <scale>0.8</scale>
        <Icon>
          <href>https://www.gpsies.com/images/waypointIcons/generic.png</href>
        </Icon>
      </IconStyle>
      <LabelStyle>
        <scale>0</scale>
      </LabelStyle>
      <BalloonStyle>
        <text>$[description]</text>
      </BalloonStyle>
    </Style>
    <Style id="generic_h">
      <IconStyle>
        <scale>0.8</scale>
        <Icon>
          <href>https://www.gpsies.com/images/waypointIcons/generic.png</href>
        </Icon>
      </IconStyle>
      <LabelStyle>
        <scale>1</scale>
      </LabelStyle>
      <BalloonStyle>
        <text>$[description]</text>
      </BalloonStyle>
    </Style>
    <StyleMap id="generic">
      <Pair>
        <key>normal</key>
        <styleUrl>#generic_n</styleUrl>
      </Pair>
      <Pair>
        <key>highlight</key>
        <styleUrl>#generic_h</styleUrl>
      </Pair>
    </StyleMap>
            """)

    cnt = 0 
    for vessel in results:
        if vessel['price'] >= -1:
            cnt += 1
            link = [ch for ch in vessel['link'] if (ch >= 'a' and ch <= 'z') or ch in ['-', '_', '/', '.'] or (ch >= '0' and ch <= '9') ]
            f.write(f"""    
        <Placemark>
        <name>---{vessel['price']}--- {''.join(link)}</name>
        <styleUrl>#generic</styleUrl>
        <Point>
            <coordinates>{vessel['lat']},{vessel['long']},0</coordinates>
        </Point>
        </Placemark>
                    """)
            
    f.write("""
                
                        
    </Document>
    </kml>


                """)
    print(f'total no price: {skipped_because_no_price}')
    print(f'total found: {cnt}')
        